drop table if exists FILMS cascade;
drop table if exists mov_users cascade;
drop table if exists mpa cascade;
drop table if exists likes cascade;
drop table if exists genres cascade;
drop table if exists friends cascade;
drop table if exists films_genres cascade;

CREATE TABLE IF NOT EXISTS genres
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_genre varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_mpa varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar NOT NULL,
    description  varchar NOT NULL,
    release_date date,
    duration     integer,
    likes        integer,
    mpa          integer REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS films_genres
(
    id_film integer REFERENCES films (id),
    id_genre integer REFERENCES genres (id),
    CONSTRAINT film_genre PRIMARY KEY (id_film,id_genre)
);

CREATE TABLE IF NOT EXISTS mov_users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar NOT NULL UNIQUE,
    login    varchar NOT NULL UNIQUE,
    name     varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS friends
(
    id_user integer REFERENCES mov_users (id),
    id_friend integer REFERENCES mov_users (id),
    CONSTRAINT user_friend PRIMARY KEY (id_user,id_friend)
);

CREATE TABLE IF NOT EXISTS likes
(
    id_user integer REFERENCES mov_users (id),
    id_film integer REFERENCES films (id),
    CONSTRAINT user_film PRIMARY KEY (id_user,id_film)
);

