drop table if exists FILMS cascade;
drop table if exists mov_users cascade;
drop table if exists mpa cascade;
drop table if exists likes cascade;
drop table if exists genres cascade;
drop table if exists friends cascade;
drop table if exists films_genres cascade;

CREATE TABLE IF NOT EXISTS genres
(
    id_genre   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_genre varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa
(
    id_mpa   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_mpa varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    id_film      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_film    varchar NOT NULL,
    description  varchar NOT NULL,
    release_date date,
    duration     integer,
    likes        integer,
    mpa          integer REFERENCES mpa (id_mpa)
);

CREATE TABLE IF NOT EXISTS films_genres
(
    id_film  integer REFERENCES films (id_film),
    id_genre integer REFERENCES genres (id_genre)
);

CREATE TABLE IF NOT EXISTS mov_users
(
    id_user  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar NOT NULL,
    login    varchar NOT NULL,
    name     varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS friends
(
    id_user   integer REFERENCES mov_users (id_user),
    id_friend integer REFERENCES mov_users (id_user)
);

CREATE TABLE IF NOT EXISTS likes
(
    id_user integer REFERENCES mov_users (id_user),
    id_film integer REFERENCES films (id_film)
);

